// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;
/// <summary>
///     3othaymen2
/// </summary>
//[Table("Eothaymen2" )]
public partial class Eothaymen2
{
    [Key]
 
    public int Id { get; set; }

    [Required]
 
    public string Nass { get; set; }

    [Required]
 
    public string Title { get; set; }

 
    public int Pageid { get; set; }
}