// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
/// <summary>
/// old a7kam
/// </summary>
[OldName("A7kam")]
[Keyless]
//[Table("ahkam" )]
public partial class Ahkam
{
    [OldName("QuranID")]
 
    public int? QuranId { get; set; }

    [OldName("Verse")]
    public string Verse { get; set; }

    [OldName("GVerse")]
   
    public string Gverse { get; set; }

    [OldName("Meaning1")]
    public string Meaning1 { get; set; } //TODO: what is the difference between Meaning1 and Meaning2

    [OldName("Meaning2")]
    public string Meaning2 { get; set; }//TODO: what is the difference between Meaning1 and Meaning2

    [OldName("English")]
    public string English { get; set; }

    [OldName("Germany")]
    public string Germany { get; set; }

    [OldName("PageNo")]
    public int? PageNo { get; set; }

    [OldName("PartNo")]
    public int? PartNo { get; set; }

    [OldName("VerseNo")]
    public int? VerseNo { get; set; }

    [OldName("SuraName")]
    [StringLength(50)]
    public string SuraName { get; set; }

    [OldName("SuraNo")]
    public int? SuraNo { get; set; }

    //[OldName("tabary")]
    //// [Column("tabary")]
    //public string Tabary { get; set; }

    //[OldName("kortoby")]
    //// [Column("kortoby")]
    //public string Kortoby { get; set; }

    //[OldName("safwa")]
    //// [Column("safwa")]
    //public string Safwa { get; set; }

    [OldName("ibnkathir")]
 
    public string Ibnkathir { get; set; }

    //[OldName("kashaf")]
    //// [Column("kashaf")]
    //public string Kashaf { get; set; }

    [OldName("zelal")]
 
    public string Zelal { get; set; }

    [OldName("sa3dy")]
 
    public string Saady { get; set; } 

    [OldName("kadeer")]
 
    public string Kadeer { get; set; }

    [OldName("wa7dy")]
 
    public string Wahdy { get; set; }
    
    [OldName("id")]
    [Key]
     
    public int Id { get; set; }

    [OldName("araby")]
    [Required]
  
    public string Araby { get; set; }

    [OldName("gasas")]
    [Required]
 
    public string Gasas { get; set; }

    [OldName("rwaee")]
    [Required]
   
    public string Rwaee { get; set; } //TODO: Referes to what 

    //[OldName("gah")]
    //[Required]
    //// [Column("gah")]
    //public string Gah { get; set; } //TODO: Referes to what 

    [OldName("maram")]
    [Required]
 
    public string Maram { get; set; }

    [OldName("kia")]
    [Required]
 
    public string Kia { get; set; } //TODO: Referes to what 

    [OldName("make")]
 
    public int Make { get; set; } //TODO: Referes to what 
}