// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
/// <summary>
/// old a7kam
/// </summary>
public partial class Ahkam
{

    public int Id { get; set; }

    public int? QuranId { get; set; }

    public string Verse { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    public int? SuraNo { get; set; }

    public string SuraName { get; set; }

    public string Araby { get; set; }//TODO: Referes to what  => ابن العربي 

    public string Gasas { get; set; }//TODO: Referes to what  => الجصاص

    public string Rwaee { get; set; } //TODO: Referes to what => روائع البيان

    public string Gah { get; set; } //TODO: Referes to what  => الجهضمي

    public string Maram { get; set; }//TODO: Referes to what  => نيل المرام

    public string Kia { get; set; } //TODO: Referes to what  => كيا هرسي

}