// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("ahkam_book")]
public partial class AhkamBook
{
    [OldName("id")]
    [Key]
 
    public int Id { get; set; }

    [OldName("book")]
    [Required]
 
    public string BookName { get; set; }

    [OldName("Field_q")]
    [Required]
  
    public string MappedColumnName  { get; set; } 

}