// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("ahkam_book")]
[Index("Feature", Name = "feature")]
public partial class AhkamBook
{
    [OldName("id")]
    [Key]
 
    public int Id { get; set; }

    [OldName("book")]
    [Required]
 
    public string BookName { get; set; }

    [OldName("Field_q")]
    [Required]
  
    public string MappedColumnName  { get; set; } 

    //[OldName("details")]
    //[Required]
    //// [Column("details")]
    //public string Details { get; set; }

    [OldName("feature")]
 
    public int Feature { get; set; } //TODO : for what is this column 

    [OldName("date")]
 
    public int Date { get; set; } //TODO : for what is this column

    [OldName("active")]
   
    public short Active { get; set; } //TODO : for what is this column
}