// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Asbab
{
    public int QuranId { get; set; } //TODO : should be a forign key to Quran table and primary key for the same table 

    public int? PageNo { get; set; }

    public int? VerseNo { get; set; }

    public string Verse { get; set; }//TODO : should be deleted 

    public int? SuraNo { get; set; }

    public string SuraName { get; set; }

    public string Lebab { get; set; } //TODO: Referes to what  => لباب النقول

    public string Mosnad { get; set; }//TODO: Referes to what  => صحيح المسند من اسباب النزول
    
    public string Eegab { get; set; } // TODO: Referes to what  => العجاب في بيان الاسباب

    public string Esteaab { get; set; } //TODO: Referes to what  => الاستيعاب في بيان الاسباب

    public string Moharrer { get; set; } //TODO: Referes to what  => المحرر في اسباب النزول
}