// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("AsbabBook")]
//[Table("asbab_book")]
// [Index("Feature", Name = "feature")]
public partial class AsbabBook
{
    [OldName("id")]
    [Key]
    public int Id { get; set; }

    [OldName("book")]
    [Required]
    public string Book { get; set; }

    [OldName("Field_q")]
    [Required]
    public string MappedColumnName { get; set; }

    [OldName("details")]
    [Required]
    public string Details { get; set; }

    [OldName("feature")]
    public int Feature { get; set; }

    [OldName("date")]
    public int Date { get; set; }

    [OldName("active")]
    public short Active { get; set; }
}