// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("chapter")]
//[Table("chapter")]
public partial class Chapter
{
    [OldName("id")]
    [Key]
    public int Id { get; set; }

    [OldName("chapter_id")]
    public int ChapterId { get; set; } //TODO: if it isn't a forignkey change to ChapterNumber  

    [OldName("name")]
    [Required]
    public string Name { get; set; }

    [OldName("book_id")]
    public int BookId { get; set; }
}