﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class MogamChapter //TODO: rename to MogamChapter
{
    public int Id { get; set; }

    public int ChapterId { get; set; } //TODO: if it isn't a forignkey change to ChapterNumber  دول متخزن فيهم ارقامهم على حسب حروف اللغه العربيه 

    public string Name { get; set; }


    public int BookId { get; set; } // Foreign key to MogamBook 1,10,20
    //public MogamBook MogamBook { get; set; } // Navigation property

    //public ICollection<MogamBab> MogamBabs { get; set; }

}