// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;

[Table("e3gaz_bab", Schema = "quran_quran2")]
[Index("BabId", Name = "bab_id")]
[Index("ChapterId", Name = "chapter_id")]
[Index("E3gazBookId", Name = "e3gaz_book_id")]
[Index("Id", Name = "id")]
public partial class EgazBab
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Column("e3gaz_book_id")]
    public int EgazBookId { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("bab_id")]
    public int BabId { get; set; }

    // Navigation
    [ForeignKey(nameof(EgazBookId))]
    public EgazBook Book { get; set; }

    [ForeignKey(nameof(ChapterId))]
    public EgazChapter Chapter { get; set; }

    public ICollection<EgazSubBab> SubBabs { get; set; }
    public ICollection<EgazItem> Items { get; set; }
}
