// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("E3gazBab")]
public partial class EgazBab
{
    [OldName("id")]
    [Key]
    public int Id { get; set; }

    [OldName("chapter_id")]
    public int EgazChapterId { get; set; }

    [OldName("e3gaz_book_id")]
    public int EgazBookId { get; set; }

    [OldName("name")]
    [Required]
    public string Name { get; set; }

    [OldName("bab_id")]
    public int BabId { get; set; }

    // Navigation
    // [ForeignKey(nameof(EgazBookId))]
    // public EgazBook EgazBook { get; set; }

    // [ForeignKey(nameof(ChapterId))]
    // public EgazChapter EgazChapter { get; set; }

    // public ICollection<EgazSubBab> SubBabs { get; set; }
    // public ICollection<EgazItem> Items { get; set; }
}