// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("e3gaz_sub_bab")]
public partial class EgazSubBab
{
    [OldName("id")]
    [Key]
    public int Id { get; set; }

    [OldName("chapter_id")]
    public int EgazChapterId { get; set; }

    [OldName("e3gaz_book_id")]
    public int EgazBookId { get; set; }

    [OldName("name")]
    [Required]
    public string Name { get; set; }

    [OldName("bab_id")]
    public int EgazBabId { get; set; }

    [OldName("sub_bab_id")]
    public int SubBabId { get; set; } //مفيش فرق بينه و بين id

    //// Navigation
    //[ForeignKey(nameof(EgazBookId))]
    //public EgazBook EgazBook { get; set; }

    //[ForeignKey(nameof(ChapterId))]
    //public EgazChapter EgazChapter { get; set; }

    //[ForeignKey(nameof(BabId))]
    //public EgazBab EgazBab { get; set; }

    //public ICollection<Egaz> Items { get; set; }
}