﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class EgazBook
{
    public int Id { get; set; }

    public string Book { get; set; }

    public string MappedColumnName { get; set; }//TODO: Rename to not used 


    // // Navigation
    // public ICollection<EgazChapter> Chapters { get; set; }
    // public ICollection<EgazBab> Babs { get; set; }
    // public ICollection<EgazSubBab> SubBabs { get; set; }
    // public ICollection<Egaz> Items { get; set; }
}