﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;


public partial class Egaz 
{
    public int Id { get; set; }

    [OldName("matn")]
    [Required]
    public string Matn { get; set; }
    
    public int EgazChapterId { get; set; }
    
    public int EgazBabId { get; set; }
    
    public int EgazSubBabId { get; set; }//TODO : We Can move the sub bab to babs
    
    public int EgazBookId { get; set; }

    // Navigations
    // [ForeignKey(nameof(EgazBookId))]
    // public EgazBook EgazBook { get; set; }

    // [ForeignKey(nameof(ChapterId))]
    // public EgazChapter EgazChapter { get; set; }

    // [ForeignKey(nameof(BabId))]
    // public EgazBab EgazBab { get; set; }

    // [ForeignKey(nameof(SubBabId))]
    // public EgazSubBab EgazSubBab { get; set; }
}