// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

/// <summary>
/// old name: E3gaz Table
/// </summary>
[OldName("e3gaz")]
//[Table("e3gaz")]
public partial class Egaz 
{
    [OldName("id")]
    [Key]
    public int Id { get; set; }

    [OldName("matn")]
    [Required]
    public string Matn { get; set; }
    
    [OldName("chapter_id")]
    public int EgazChapterId { get; set; }
    
    [OldName("bab_id")]
    public int EgazBabId { get; set; }
    
    [OldName("sub_bab_id")]
    public int EgazSubBabId { get; set; }
    
    [OldName("e3gaz_book_id")]
    public int EgazBookId { get; set; }

    // Navigations
    // [ForeignKey(nameof(EgazBookId))]
    // public EgazBook EgazBook { get; set; }

    // [ForeignKey(nameof(ChapterId))]
    // public EgazChapter EgazChapter { get; set; }

    // [ForeignKey(nameof(BabId))]
    // public EgazBab EgazBab { get; set; }

    // [ForeignKey(nameof(SubBabId))]
    // public EgazSubBab EgazSubBab { get; set; }
}