// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("e3gaz_book")]
public partial class EgazBook
{
    [OldName("id")]
    [Key]
    public int Id { get; set; }

    [OldName("book")]
    [Required]
    public string Book { get; set; }

    [OldName("Field_q")]
    [Required]
    public string MappedColumnName { get; set; }//TODO: Rename to not used 


    // // Navigation
    // public ICollection<EgazChapter> Chapters { get; set; }
    // public ICollection<EgazBab> Babs { get; set; }
    // public ICollection<EgazSubBab> SubBabs { get; set; }
    // public ICollection<Egaz> Items { get; set; }
}