// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("e3gaz_book")]
// //[Table("e3gaz_book")]
// [Index("Feature", Name = "feature")]
// [Index("Id", Name = "id")]
public partial class EgazBook
{
    [OldName("id")]
    [Key]
    public int Id { get; set; }

    [OldName("book")]
    [Required]
    public string Book { get; set; }

    [OldName("Field_q")]
    [Required]
    public string MappedColumnName { get; set; }

    //[OldName("details")]
    //[Required]
    //public string Details { get; set; }

    //[OldName("feature")]
    //public int Feature { get; set; } // TODO: For what?

    //[OldName("date")]
    //public int Date { get; set; }

    //[OldName("active")]
    //public short Active { get; set; } //TODO: is it used ?

    // // Navigation
    // public ICollection<EgazChapter> Chapters { get; set; }
    // public ICollection<EgazBab> Babs { get; set; }
    // public ICollection<EgazSubBab> SubBabs { get; set; }
    // public ICollection<Egaz> Items { get; set; }
}