// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;
/// <summary>
/// old name : e3gaz_chapters
/// </summary>
 
[Index("ChapterId", Name = "chapter_id")]
[Index("E3gazBookId", Name = "hadith_bab_id_idx")]
public partial class EgazChapter
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }
    /// <summary>
    /// old name : e3gaz_book_id
    /// </summary>
 
    public int EgazBookId { get; set; }
    /// <summary>
    /// old name : chapter_id
    /// </summary>
 
    public int ChapterId { get; set; }

 
    //[ForeignKey(nameof(EgazBookId))]
    //public EgazBook Book { get; set; }

    //public ICollection<EgazBab> Babs { get; set; }
    //public ICollection<EgazSubBab> SubBabs { get; set; }
    //public ICollection<Egaz> Items { get; set; }
}
