﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class EgazChapter
{
    public int Id { get; set; }

 
    [StringLength(255)]
    public string Name { get; set; }
    
    public int EgazBookId { get; set; }
    
 
    public int EgazChapterId { get; set; }

    //[ForeignKey(nameof(EgazBookId))]
    //public EgazBook EgazBook { get; set; }

    //public ICollection<EgazBab> EgazBabs { get; set; }
    //public ICollection<EgazSubBab> EgazSubBabs { get; set; }
    //public ICollection<Egaz> EgazItems { get; set; } //TODO:rename to EgazItems
}