﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class EgazBab
{
    public int Id { get; set; }

    public int EgazChapterId { get; set; }

    public int EgazBookId { get; set; }

    public string Name { get; set; }

    public int BabId { get; set; }

    // Navigation
    // [ForeignKey(nameof(EgazBookId))]
    // public EgazBook EgazBook { get; set; }

    // [ForeignKey(nameof(ChapterId))]
    // public EgazChapter EgazChapter { get; set; }

    // public ICollection<EgazSubBab> SubBabs { get; set; }
    // public ICollection<EgazItem> Items { get; set; }
}