﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class EgazSubBab
{
    public int Id { get; set; }

    public int EgazChapterId { get; set; }

    public int EgazBookId { get; set; }

    public string Name { get; set; }

    public int EgazBabId { get; set; }

    public int SubBabId { get; set; } //مفيش فرق بينه و بين id

    //// Navigation
    //[ForeignKey(nameof(EgazBookId))]
    //public EgazBook EgazBook { get; set; }

    //[ForeignKey(nameof(ChapterId))]
    //public EgazChapter EgazChapter { get; set; }

    //[ForeignKey(nameof(BabId))]
    //public EgazBab EgazBab { get; set; }

    //public ICollection<Egaz> Items { get; set; }
}