// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;

/// <summary>
/// old name: E3gaz Table
/// </summary>
 
public partial class Egaz 
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("matn")]
    public string Matn { get; set; }
    /// <summary>
    /// old name: chapter_id
    /// </summary>
 
    public int ChapterId { get; set; }
    /// <summary>
    /// old name: bab_id
    /// </summary>
   
    public int BabId { get; set; }
    /// <summary>
    /// old name: sub_bab_id
    /// </summary>
   
    public int SubBabId { get; set; }
    /// <summary>
    /// old name: e3gaz_book_id
    /// </summary>
 
    public int EgazBookId { get; set; }

    // Navigations
    [ForeignKey(nameof(EgazBookId))]
    public EgazBook Book { get; set; }

    [ForeignKey(nameof(ChapterId))]
    public EgazChapter Chapter { get; set; }

    [ForeignKey(nameof(BabId))]
    public EgazBab Bab { get; set; }

    [ForeignKey(nameof(SubBabId))]
    public EgazSubBab SubBab { get; set; }
}
