﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;


public partial class Erab
{
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    public int? SuraNo { get; set; }

    public string SuraName { get; set; } 

    public string Nahas { get; set; }

    //[OldName("bakoly")]
    //public string Bakoly { get; set; }

    //[OldName("akbry")]
    //public string Akbry { get; set; }

    public string Kharat { get; set; }

    public string Daas { get; set; } //TODO: rename this columns to something more meaningfull

    public string Tbian { get; set; }

    public string Gadwal { get; set; }

    public string Darwish { get; set; }
}