// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("e3rab")]

public partial class Erab
{
    [OldName("QuranID")]
    public int? QuranId { get; set; }

    [OldName("PageNo")]
    public int? PageNo { get; set; }

    [OldName("PartNo")]
    public int? PartNo { get; set; }

    [OldName("VerseNo")]
    public int? VerseNo { get; set; }

    [OldName("SuraNo")]
    public int? SuraNo { get; set; }

    [OldName("SuraName")]
    public string SuraName { get; set; }

    [OldName("na7as")]
    public string Nahas { get; set; }

    [OldName("bakoly")]
    public string Bakoly { get; set; }

    [OldName("akbry")]
    public string Akbry { get; set; }

    [OldName("kharat")]
    public string Kharat { get; set; }

    [OldName("daas")]
    public string Daas { get; set; } //TODO: rename this columns to something more meaningfull

    [OldName("tbian")]
    public string Tbian { get; set; }

    [OldName("gadwal")]
    public string Gadwal { get; set; }

    [OldName("darwish")]
    public string Darwish { get; set; }
}