// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;
/// <summary>
/// old name : E3rabBook
/// </summary>
 
public partial class ErabBook
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("book")]
    public string Book { get; set; }

    [Column("Field_q")]
    public string FieldQ { get; set; }
}