// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
 
/// <summary>
/// old name: KaratQuranOrg
/// </summary>
public partial class KaratQuranOrg
{
    /// <summary>
    /// old name: QuranID
    /// </summary>
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }
    public int? PartNo { get; set; }
    public int? VerseNo { get; set; }

    public string VerseNoAr { get; set; }
    public int? SuraNo { get; set; }

    /// <summary>
    /// old name: SuraName
    /// </summary>
    [StringLength(250)]
    public string SuraName { get; set; }

    /// <summary>
    /// old name: karat_vers
    /// </summary>
    public int? KaratVers { get; set; }

    /// <summary>
    /// old name: karat_page
    /// </summary>
    public int? KaratPage { get; set; }

    /// <summary>
    /// old name: karat_type
    /// </summary>
    public int? KaratType { get; set; }

    //// Navigation Property to Quran
    //[ForeignKey(nameof(QuranId))]
    //public Quran Quran { get; set; }
}
