// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("KaratQuranOrg")]
public partial class KaratQuranOrg
{
    [OldName("QuranID")]
    public int? QuranId { get; set; }

    [OldName("PageNo")]
    public int? PageNo { get; set; }
    
    [OldName("PartNo")]
    public int? PartNo { get; set; }
    
    [OldName("VerseNo")]
    public int? VerseNo { get; set; }

    [OldName("VerseNoAr")]
    public string VerseNoAr { get; set; }
    
    [OldName("SuraNo")]
    public int? SuraNo { get; set; }

    [OldName("SuraName")]
    [StringLength(250)]
    public string SuraName { get; set; }

    [OldName("karat_vers")]
    public int? KaratVers { get; set; }

    [OldName("karat_page")]
    public int? KaratPage { get; set; }

    [OldName("karat_type")]
    public int? KaratType { get; set; }

    //// Navigation Property to Quran
    //[ForeignKey(nameof(QuranId))]
    //public Quran Quran { get; set; }
}