// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;
/// <summary>
/// old name karat_quran
/// </summary>
[Keyless]

 
public partial class KaratQuran
{
    /// <summary>
    /// old name: id
    /// </summary>
    public int? Id { get; set; }

    /// <summary>
    /// old name: QuranID
    /// </summary>
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }
    public int? PartNo { get; set; }
    public int? VerseNo { get; set; }

    public string VerseNoAr { get; set; }
    public int? SuraNo { get; set; }
    public string SuraName { get; set; }

    /// <summary>
    /// old name: karat_vers
    /// </summary>
    public int? KaratVers { get; set; }

    /// <summary>
    /// old name: karat_page
    /// </summary>
    public int? KaratPage { get; set; }

    /// <summary>
    /// old name: karat_type
    /// </summary>
    public int? KaratType { get; set; }

    /// <summary>
    /// old name: status
    /// </summary>
    public int? Status { get; set; }

    /// <summary>
    /// old name: status_fullImg
    /// </summary>
    public int? StatusFullImg { get; set; }

    /// <summary>
    /// old name: code_img
    /// </summary>
    public string CodeImg { get; set; }

    /// <summary>
    /// old name: master
    /// </summary>
    public int? Master { get; set; }

    /// <summary>
    /// old name: mp3
    /// </summary>
    public int? Mp3 { get; set; }

    /// <summary>
    /// old name: upd
    /// </summary>
    public short? Upd { get; set; }

    /// <summary>
    /// old name: up_time
    /// </summary>
    public DateTime? UpTime { get; set; }
    //[ForeignKey(nameof(QuranId))]
    //public Quran Quran { get; set; }
}
