﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
public partial class KaratQuranOrg // مش مكتوب عند عباس 
{

    public int Id { get; set; }
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }
    
    public int? PartNo { get; set; }
    
    public int? VerseNo { get; set; }

    public string VerseNoAr { get; set; }
    
    public int? SuraNo { get; set; }

    [StringLength(250)]
    public string SuraName { get; set; }

    //[OldName("karat_vers")]
    //public int? KaratVers { get; set; }

    //[OldName("karat_page")]
    //public int? KaratPage { get; set; }

    //[OldName("karat_type")]
    //public int? KaratType { get; set; }

    //// Navigation Property to Quran
    //[ForeignKey(nameof(QuranId))]
    //public Quran Quran { get; set; }
}