// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("karat_quran")]
public partial class KaratQuran
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("QuranID")]
    public int? QuranId { get; set; }

    [OldName("PageNo")]
    public int? PageNo { get; set; }
    
    [OldName("PartNo")]
    public int? PartNo { get; set; }
    
    [OldName("VerseNo")]
    public int? VerseNo { get; set; }

    [OldName("VerseNoAr")]
    public string VerseNoAr { get; set; }
    
    [OldName("SuraNo")]
    public int? SuraNo { get; set; }
    
    [OldName("SuraName")]
    public string SuraName { get; set; }

    [OldName("karat_vers")]
    public int? KaratVers { get; set; }

    [OldName("karat_page")]
    public int? KaratPage { get; set; }

    [OldName("karat_type")]
    public int? KaratType { get; set; } //TODO: is this is a foreign key

    [OldName("status")]
    public int? Status { get; set; }

    [OldName("status_fullImg")]
    public int? StatusFullImg { get; set; }

    [OldName("code_img")]
    public string CodeImg { get; set; }

    [OldName("master")]
    public int? Master { get; set; }

    [OldName("mp3")]
    public int? Mp3 { get; set; }

    [OldName("upd")]
    public short? Upd { get; set; } //TODO: for what is this column

    [OldName("up_time")]
    public DateTime? UpTime { get; set; } //TODO: for what is this column
    
    //[ForeignKey(nameof(QuranId))]
    //public Quran Quran { get; set; }
}