﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class KaratQuran // مش مكتوب عند عباس 
{
    public int? Id { get; set; }

    public int? QuranId { get; set; }

    public int? PageNo { get; set; }
    
    public int? PartNo { get; set; }
    
    public int? VerseNo { get; set; }

    public string VerseNoAr { get; set; }
    
    public int? SuraNo { get; set; }
    
    public string SuraName { get; set; }

    public int? KaratVers { get; set; }

    public int? KaratPage { get; set; }

    public int? KaratId { get; set; } 

    public int? Status { get; set; }

    public int? StatusFullImg { get; set; }

    public string CodeImg { get; set; }

    public int? Master { get; set; }

    public int? Mp3 { get; set; }

    public short? Upd { get; set; } //TODO: for what is this column

    public DateTime? UpTime { get; set; } //TODO: Upload time 

    //[ForeignKey(nameof(QuranId))]
    //public Quran Quran { get; set; }
}