﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
public partial class KeratAashr// مش مكتوب عند عباس 
{
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }
    
    public string MaanyText { get; set; } //TODO: Rename this property to something more meaningful why this is here ? isn't it the same as MaanyText in Ma3any

    public string Farsh { get; set; } //TODO: Rename this property to something more meaningful
}