// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[Keyless]
[OldName("kerat")]
public partial class Kerat
{
    [OldName("QuranID")]
    public int? QuranId { get; set; }

    [OldName("Verse")]
    public string Verse { get; set; }

    [OldName("GVerse")]
    public string Gverse { get; set; }

    [OldName("PageNo")]
    public int? PageNo { get; set; }
    
    [OldName("PartNo")]
    public int? PartNo { get; set; }
    
    [OldName("VerseNo")]
    public int? VerseNo { get; set; }

    [OldName("SuraName")]
    [StringLength(50)]
    public string SuraName { get; set; }

    [OldName("SuraNo")]
    public int? SuraNo { get; set; }

    [OldName("ma3any")]
    public string Maany { get; set; } //TODO: there is no data in this column except QuranID 4278, 4283, 4284, 4286 

    // Navigation Property to Quran
    //[ForeignKey(nameof(QuranId))]
    //public Quran Quran { get; set; }
}