// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
 
public partial class Kerat3ashr
{
    [Column("QuranID")]
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }
    /// <summary>
    /// old name: ma3any
    /// </summary>
    [Column("maany")]
    public string Maany { get; set; }

    [Column("farsh")]
    public string Farsh { get; set; }
}