// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
//[Table("kerat", Schema = "quran_quran2")]
/// <summary>
/// old name: Kerat
/// </summary>
public partial class Kerat
{
    /// <summary>
    /// old name: QuranID
    /// </summary>
    public int? QuranId { get; set; }

    /// <summary>
    /// old name: Verse
    /// </summary>
    public string Verse { get; set; }

    /// <summary>
    /// old name: GVerse
    /// </summary>
    [Column("GVerse")]
    public string Gverse { get; set; }

    public int? PageNo { get; set; }
    public int? PartNo { get; set; }
    public int? VerseNo { get; set; }

    /// <summary>
    /// old name: SuraName
    /// </summary>
    [StringLength(50)]
    public string SuraName { get; set; }

    public int? SuraNo { get; set; }

    /// <summary>
    /// old name: ma3any
    /// </summary>
    [Column("maany")]
    public string Maany { get; set; }

    // Navigation Property to Quran
    //[ForeignKey(nameof(QuranId))]
    //public Quran Quran { get; set; }
}