// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("ma3any_book")]
public partial class Ma3anyBook
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("name")]
    public string Name { get; set; }

    // [OldName("about")]
    // public string About { get; set; } // TODO: for what is this column

    // [OldName("date")]
    // public int? Date { get; set; } // TODO: for what is this column
}