// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Maany
{ 
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }

    public string? Text { get; set; }
    
    public int? MaanyBookId { get; set; }
    //public  MaanyBook? MaanyBook { get; set; } // Navigation property
}