// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;
/// <summary>
/// old name: ma3any
/// </summary>
[Keyless]

[Table("maany", Schema = "quran_quran2")]
public partial class Maany
{
    [Column("QuranID")]
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }

    /// <summary>
    /// old name: ma3any
    /// </summary>
    [Column("maany")]
    public string Maany1 { get; set; }
    /// <summary>
    /// old name: book_id
    /// </summary>
    [Column("book_id")]
    public int? BookId { get; set; }
}