// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
public partial class MaanyBook
{
    public int Id { get; set; }

    public string Name { get; set; }
    //ناقص كتاب مخلوف ف الداتا

    //public virtual ICollection<Maany>? Maanies { get; set; } = new List<Maany>();
}