﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
public partial class MofradWord // مش مكتوب عند عباس 
{
    public int? Id { get; set; }

    public string Word { get; set; }

    public string Details { get; set; }

    public int? Letter { get; set; }
    //TODO:Look for the relations between MofradWord and MofradLetter or other tables 
}