// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("mofradat")]

public partial class Mofradat
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("nass")]
    public string Nass { get; set; }

    [OldName("title")]
    public string Title { get; set; }

    [OldName("pageid")]
    public int? Pageid { get; set; }
}