// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("mofrad_words")]
public partial class MofradWord
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("word")]
    public string Word { get; set; }

    [OldName("details")]
    public string Details { get; set; }

    [OldName("letter")]
    public int? Letter { get; set; }
    //TODO:Look for the relations between MofradWord and MofradLetter or other tables 
}