// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("mofrad_letters")]
public partial class MofradLetter // ممكن يكون واخد دول راسمهم في الحاجات زي فهرس بداية الايات
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("letter")]
    public string Letter { get; set; }
}