// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("bab")]
public partial class MogamBab
{
    [OldName("id")]
    public int Id { get; set; }

    [OldName("chapter_id")]
    public int ChapterId { get; set; }

    [OldName("bab_id")]
    public int BabId { get; set; }

    [OldName("name")]
    public string Name { get; set; }
    
    [OldName("MogamBookId")]
    public int MogamBookId { get; set; }

    //[ForeignKey(nameof(MogamBookId))]
    //public MogamBook MogamBook { get; set; }
}