// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("mogam_words")]
public partial class MogamWord // عباس بيقول انها مستخدمه في فهرس بداية الايات 
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("word")]
    public string Word { get; set; }

    [OldName("letter")]
    public int? LetterId { get; set; }

    [OldName("sura")]
    public int? SuraNumber { get; set; }

    [OldName("aya")]
    public int? AyaNumber { get; set; }

    [OldName("type")]
    public string Type { get; set; }

    [OldName("pageno")]
    public int? PageNumber { get; set; }
}