// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("mogam")]
public partial class Mogam
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("chapter_id")]
    public int? ChapterId { get; set; }

    [OldName("bab_id")]
    public int? BabId { get; set; }

    [OldName("1text")]
    public string _1text { get; set; } //TODO: why this is named like that ?  rename it to something more meaningfull

    [OldName("bab_name")]
    public string BabName { get; set; }

    [OldName("text")]
    public string Text { get; set; }// TODO : what is this column for ?

    [OldName("book_id")]
    public int? BookId { get; set; } // TODO : this is foreign key to which table ?
                                     // public  MogamBook? Book { get; set; } // Navigation property
}