﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class MogamBab
{
    public int Id { get; set; }

    public int MogamChapterId { get; set; }

    public string Name { get; set; }
    
    public int MogamBookId { get; set; }

    //[ForeignKey(nameof(MogamBookId))]
    //public MogamBook MogamBook { get; set; }

    //[ForeignKey(nameof(MogamChapterId))]
    //public Chapter MogamChapter { get; set; }

}