// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;
/// <summary>
/// old table name: Bab
/// </summary>
[Table("MogamBab")]
public partial class MogamBab
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Column("bab_id")]
    public int BabId { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }
    /// <summary>
    /// older name: BookId
    /// </summary>
    [Column("MogamBookId")]
    public int MogamBookId { get; set; }

    //[ForeignKey(nameof(MogamBookId))]
    //public MogamBook MogamBook { get; set; }
}