// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("mogam")]
public partial class Mogam
{
    [OldName("id")]
    public int? Id { get; set; }

    //[OldName("1text")]
    //public string _1text { get; set; } 

    [OldName("bab_name")]
    public string BabName { get; set; }

    [OldName("text")]
    public string Nass { get; set; }

    //Navigation Properties
    [OldName("chapter_id")]
    public int? MogamChapterId { get; set; }

    [OldName("bab_id")]
    public int? MogamBabId { get; set; }

    [OldName("book_id")]
    public int? MogamBookId { get; set; }

    //public  MogamBook? MogamBook { get; set; } // Navigation property
    //public MogamChapter? MogamChapter { get; set; } // Navigation property
    //public MogamBab? MogamBab { get; set; } // Navigation property
}