﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
public partial class Mogam
{
    public int? Id { get; set; }

    //[OldName("1text")]
    //public string _1text { get; set; } 

    public string BabName { get; set; }

    public string Nass { get; set; }//1text

    //Navigation Properties
    public int? MogamChapterId { get; set; }

    public int? MogamBabId { get; set; }

    public int? MogamBookId { get; set; }

    //public  MogamBook? MogamBook { get; set; } // Navigation property
    //public MogamChapter? MogamChapter { get; set; } // Navigation property
    //public MogamBab? MogamBab { get; set; } // Navigation property
}