// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("moshabeh1")]
public partial class Moshabeh1
{
    [OldName("QuranID")]
    public int? QuranId { get; set; } // navigation property

    [OldName("PageNo")]
    public int? PageNumber { get; set; }

    [OldName("ma3any")]
    public string Maany { get; set; }
    // Navigation Property to Quran
    //[ForeignKey(nameof(QuranId))]
    //public Quran Quran { get; set; }
}