// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("multimedia")]

public partial class Multimedia
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("src")]
    public string Src { get; set; }


    [OldName("title")]
    public string Title { get; set; }

    [OldName("lecturer")]
    public int? Lecturer { get; set; }

    //[OldName("sura")]
    //public int? Sura { get; set; }

    [OldName("type")]
    public int? Type { get; set; }

    //[OldName("publish_status")]
    //public DateTime? PublishStatus { get; set; }

    [OldName("description")]
    public string Description { get; set; }

    [OldName("categories")]
    public int? CategoryId { get; set; }//TODO: is this a foreign key?

    [OldName("view")]
    public int? View { get; set; }


    [OldName("lang")]
    public int? LanguageId { get; set; } //TODO: is this a foreign key?

    //[OldName("user_add")]
    //public int? UserAdd { get; set; }

    [OldName("create_date")]
    public DateTime? CreateDate { get; set; }
}