﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
public partial class MultimediaCategory
{
    public int? Id { get; set; }

    [StringLength(300)]
    public string Name { get; set; }

    public int? Type { get; set; } // TODO: (غير مستخدم)

    public int? LanguageId { get; set; } // TODO: should be a forign key (غير مستخدم)

}