﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;


public partial class MultimediaLecturer
{
    public int? Id { get; set; }

    [StringLength(1000)]
    public string Name { get; set; }

    public short? Status { get; set; }

    [StringLength(800)]
    public string Image { get; set; }

    public string Descripton { get; set; }

}