// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("multimedia_categories")]
public partial class MultimediaCategory
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("name")]
    [StringLength(300)]
    public string Name { get; set; }

    [OldName("description")]
    [StringLength(500)]
    public string Description { get; set; }

    [OldName("view")]
    // [Column("view")]
    public int? View { get; set; }

    [OldName("photo")]
    [StringLength(400)]
    public string Photo { get; set; }

    [OldName("type")]
    public int? Type { get; set; }

    [OldName("sort")]
    public int? Sort { get; set; }

    // [OldName("user_add")]
    // public int? UserAdd { get; set; } 

    [OldName("create_date")]
    public DateTime? CreateDate { get; set; }

    [OldName("status")]
    public short? Status { get; set; }

    [OldName("lang")]
    public int? LanguageId { get; set; } // TODO: should be a forign key 

    [OldName("section_type")]
    public int? SectionType { get; set; }
}