﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;


public partial class Multimedia
{
    public int? Id { get; set; }

    public string Src { get; set; }


    public string Title { get; set; }

    public int? Lecturer { get; set; }

    //[OldName("sura")]
    //public int? Sura { get; set; }

    public int? Type { get; set; }

    //[OldName("publish_status")]
    //public DateTime? PublishStatus { get; set; }

    public string Description { get; set; }

    public int? CategoryId { get; set; }//TODO: is this a foreign key?

    public int? View { get; set; }


    public int? LanguageId { get; set; } //TODO: is this a foreign key?

    //[OldName("user_add")]
    //public int? UserAdd { get; set; }

    public DateTime? CreateDate { get; set; }
}