// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("multimedia_categories")]
public partial class MultimediaCategory
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("name")]
    [StringLength(300)]
    public string Name { get; set; }

    [OldName("type")]
    public int? Type { get; set; } // TODO: (غير مستخدم)

    [OldName("lang")]
    public int? LanguageId { get; set; } // TODO: should be a forign key (غير مستخدم)

}