﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class OlomChapter
{
    public int? Id { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    public int? OlomBookId { get; set; } // foreign key to OlomBook

    public int? ChapterId { get; set; } // foreign key to Chapter
}