﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class OlomSubBab
{
    public int? Id { get; set; }

    public int? ChapterId { get; set; } // Foreign Key to OlomChapter

    public int? OlomBookId { get; set; } // Foreign Key to OlomBook

    public string Name { get; set; } // Sub Bab Name

    public int? BabId { get; set; } // Foreign Key to OlomBab

    public int? SubBabId { get; set; } // Sub Bab Identifier
}