// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
////[Table("olom", Schema = "quran_quran2")]
[OldName("olom")]
public partial class Olom
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("Matn")]
    public string Matn { get; set; }

    [OldName("ChapterId")]
    public int? ChapterId { get; set; } // foreign key to OlomChapter
    [OldName("BabId")]
    public int? BabId { get; set; } // foreign key to OlomBab

    [OldName("SubBabId")]
    public int? SubBabId { get; set; } // foreign key to OlomSubBab

    [OldName("OlomBookId")]
    public int? OlomBookId { get; set; } // foreign key to OlomBook
}