// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
//[Table("olom_chapters", Schema = "quran_quran2")]
[OldName("OlomChapter")]
public partial class OlomChapter
{
    [OldName("Id")]
    public int? Id { get; set; }

    [OldName("Name")]
    [StringLength(255)]
    public string Name { get; set; }

    [OldName("OlomBookId")]
    public int? OlomBookId { get; set; } // foreign key to OlomBook

    [OldName("ChapterId")]
    public int? ChapterId { get; set; } // foreign key to Chapter
}