﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Olom 
{
    public int? Id { get; set; }

    public string Matn { get; set; }

    public int? ChapterId { get; set; } // foreign key to OlomChapter
    public int? BabId { get; set; } // foreign key to OlomBab

    public int? SubBabId { get; set; } // foreign key to OlomSubBab

    public int? OlomBookId { get; set; } // foreign key to OlomBook
}