// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
[OldName("olom")]
public partial class Olom 
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("matn")]
    public string Matn { get; set; }

    [OldName("chapter_id")]
    public int? ChapterId { get; set; } // foreign key to OlomChapter
    [OldName("bab_id")]
    public int? BabId { get; set; } // foreign key to OlomBab

    [OldName("sub_bab_id")]
    public int? SubBabId { get; set; } // foreign key to OlomSubBab

    [OldName("olom_book_id")]
    public int? OlomBookId { get; set; } // foreign key to OlomBook
}