// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
////[Table("olom_sub_bab", Schema = "quran_quran2")]
[OldName("olom_sub_bab")]
public partial class OlomSubBab
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("chapter_id")]
    public int? ChapterId { get; set; } // Foreign Key to OlomChapter

    [OldName("olom_book_id")]
    public int? OlomBookId { get; set; } // Foreign Key to OlomBook

    [OldName("name")]
    public string Name { get; set; } // Sub Bab Name

    [OldName("bab_id")]
    public int? BabId { get; set; } // Foreign Key to OlomBab

    [OldName("sub_bab_id")]
    public int? SubBabId { get; set; } // Sub Bab Identifier
}