// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
////[Table("olom_book", Schema = "quran_quran2")]
[OldName("olom_book")]
public partial class OlomBook
{
    [OldName("Id")]
    public int? Id { get; set; }

    [OldName("Book")]
    public string Book { get; set; }

    [OldName("FieldQ")]
    public string FieldQ { get; set; }

    [OldName("Details")]
    public string Details { get; set; }

    [OldName("Feature")]
    public int? Feature { get; set; }

    [OldName("Date")]
    public int? Date { get; set; }

    [OldName("Active")]
    public short? Active { get; set; }
}