// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
////[Table("olom_bab", Schema = "quran_quran2")]
[OldName("olom_bab")]
public partial class OlomBab
{
    [OldName("Id")]
    public int? Id { get; set; }

    [OldName("ChapterId")]
    public int? ChapterId { get; set; }// Foreign Key to Chapter

    [OldName("OlomBookId")]
    public int? OlomBookId { get; set; } // Foreign Key to OlomBook

    [OldName("Name")]
    public string Name { get; set; } // Name of the Bab

    [OldName("BabId")]
    public int? BabId { get; set; } // Identifier for the Bab
}