// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Aya
{
    public int? Id { get; set; }    
    public string? Verse { get; set; }
    public string VerseNoSign { get; set; }
    public int? PageNo { get; set; }
    public int? PartNo { get; set; }
    public int? HezbNo { get; set; }
    public int? RobNo { get; set; }
    public int? VerseNo { get; set; }
    public string VerseNoAr { get; set; }
    public int? SuraNo { get; set; } // Navigation property to Sura
    public string? SuraName { get; set; }
    public string? Sound { get; set; }
    public string? ImgWarsh { get; set; }
}