// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Quran_quran4Context : DbContext
{
    public Quran_quran4Context()
    {
    }

    public Quran_quran4Context(DbContextOptions<Quran_quran4Context> options)
        : base(options)
    {
    }


    public virtual DbSet<ErabBook> E3rabBooks { get; set; } //المفروض تجيب دا 


    public virtual DbSet<KaratQuranOrg> KaratQuranOrgs { get; set; }// و المفروض تجيب دا


    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Server=URANUS\\DEV;Database=Quran_quran4;User Id=ils;Password=ils@123;MultipleActiveResultSets=true;TrustServerCertificate=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
       
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}