﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Quran3 // عباس مجابش سيرتها 
{
    public int? QuranId { get; set; } // primary key

    public string Verse { get; set; }

    public string Gverse { get; set; }

    //[OldName("Sverse")]
    //public string Sverse { get; set; }
    public string Meaning1 { get; set; }
    public string Meaning2 { get; set; }
    public string English { get; set; }
    public string Germany { get; set; }
    public int? PageNo { get; set; }
    public int? PartNo { get; set; }
    public int? VerseNo { get; set; }
    [StringLength(50)]
    public string SuraName { get; set; }
    public int? SuraNo { get; set; } // navigation property to Sura

    public string Tabary { get; set; }

    public string Kortoby { get; set; }

    //[OldName("safwa")]
    //public string Safwa { get; set; }

    public string Ibnkathir { get; set; }

    public string Kashaf { get; set; }

    public string Zelal { get; set; }

    public string Sady { get; set; }

    public string Kadeer { get; set; }

    public string Wahdy { get; set; }

    public string ShortIbnkathir { get; set; }

    public string Sharawy { get; set; }

    public string Mohet { get; set; }

    public string Aysar { get; set; }

    public string Baawy { get; set; }

    public string Nasafy { get; set; }

    public string Mawrdy { get; set; }

    public string Montkab { get; set; }

    public string Hatem { get; set; }

    public string Bnothemen { get; set; }

    public string Mafateh { get; set; }

    public string Marah { get; set; }

    public string Mokatel { get; set; }

    public string Adwa { get; set; }

    public string Baedawy { get; set; }

    public string Waseet { get; set; }

    public string Alosy { get; set; }

    public string Ezzsalam { get; set; }

    public string Qatan { get; set; }

    public string Tareer { get; set; }
}