// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
////[Table("quran3", Schema = "quran_quran2")]
[OldName("quran3")]
public partial class Quran3
{
    [OldName("QuranID")]
    public int? QuranId { get; set; } // primary key

    public string Verse { get; set; }

    [OldName("GVerse")]
    public string Gverse { get; set; }

    //[OldName("Sverse")]
    //public string Sverse { get; set; }
    [OldName("Meaning1")]
    public string Meaning1 { get; set; }
    [OldName("Meaning2")]
    public string Meaning2 { get; set; }
    [OldName("English")]
    public string English { get; set; }
    [OldName("Germany")]
    public string Germany { get; set; }
    [OldName("PageNo")]
    public int? PageNo { get; set; }
    [OldName("PartNo")]
    public int? PartNo { get; set; }
    [OldName("VerseNo")]
    public int? VerseNo { get; set; }
    [OldName("SuraName")]
    [StringLength(50)]
    public string SuraName { get; set; }
    [OldName("SuraNo")]
    public int? SuraNo { get; set; } // navigation property to Sura

    [OldName("tabary")]
    public string Tabary { get; set; }

    [OldName("kortoby")]
    public string Kortoby { get; set; }

    //[OldName("safwa")]
    //public string Safwa { get; set; }

    [OldName("ibnkathir")]
    public string Ibnkathir { get; set; }

    [OldName("kashaf")]
    public string Kashaf { get; set; }

    [OldName("zelal")]
    public string Zelal { get; set; }

    [OldName("sa3dy")]
    public string Sady { get; set; }

    [OldName("kadeer")]
    public string Kadeer { get; set; }

    [OldName("wa7dy")]
    public string Wahdy { get; set; }

    [OldName("short_ibnkathir")]
    public string ShortIbnkathir { get; set; }

    [OldName("sha3rawy")]
    public string Sharawy { get; set; }

    [OldName("mo7et")]
    public string Mohet { get; set; }

    [OldName("aysar")]
    public string Aysar { get; set; }

    [OldName("ba3awy")]
    public string Baawy { get; set; }

    [OldName("nasafy")]
    public string Nasafy { get; set; }

    [OldName("mawrdy")]
    public string Mawrdy { get; set; }

    [OldName("montkab")]
    public string Montkab { get; set; }

    [OldName("hatem")]
    public string Hatem { get; set; }

    [OldName("bnothemen")]
    public string Bnothemen { get; set; }

    [OldName("mafateh")]
    public string Mafateh { get; set; }

    [OldName("mara7")]
    public string Marah { get; set; }

    [OldName("mokatel")]
    public string Mokatel { get; set; }

    [OldName("adwa")]
    public string Adwa { get; set; }

    [OldName("baedawy")]
    public string Baedawy { get; set; }

    [OldName("waseet")]
    public string Waseet { get; set; }

    [OldName("alosy")]
    public string Alosy { get; set; }

    [OldName("ezzsalam")]
    public string Ezzsalam { get; set; }

    [OldName("qatan")]
    public string Qatan { get; set; }

    [OldName("ta7reer")]
    public string Tareer { get; set; }
}