// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
////[Table("quran_sound", Schema = "quran_quran2")]
[OldName("quran_sound")]
public partial class QuranSound
{
    [OldName("QuranID")]
    public int? QuranId { get; set; }

    [OldName("verse3_old")]
    public string VerseOld { get; set; }

    [OldName("verseNoSign")]
    public string VerseNoSign { get; set; }
    [OldName("PageNo")]
    public int? PageNo { get; set; }
    [OldName("PartNo")]
    public int? PartNo { get; set; }

    [OldName("HezbNo")]
    public int? HezbNo { get; set; }

    [OldName("rob3No")]
    public int? RobNo { get; set; }
    [OldName("VerseNo")]
    public int? VerseNo { get; set; }
    [OldName("VerseNoAr")]
    public string VerseNoAr { get; set; }
    [OldName("SuraNo")]
    public int? SuraNo { get; set; } // navigation property to Sura
    [OldName("SuraName")]
    [StringLength(250)]
    public string SuraName { get; set; }

    [OldName("sound")]
    [StringLength(10)]
    public string Sound { get; set; }

    [OldName("id")]
    public int? Id { get; set; }

    [OldName("2verse")]
    public string verse { get; set; }

    [OldName("verse")]
    public string Verse { get; set; }

    [OldName("search_ayaa")]
    public string SearchAyaa { get; set; } // tODO: what is this field

    [OldName("no_of_words")]
    public int? NoOfWords { get; set; }

    [OldName("no_of_letters")]
    public int? NoOfLetters { get; set; }

    [OldName("no_of_haraka")]
    public int? NoOfHaraka { get; set; }

    [OldName("no_of_ghonna")]
    public int? NoOfGhonna { get; set; }

    [OldName("no_of_glala")]
    public int? NoOfGlala { get; set; }
}