﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class QuranSound
{
    public int? QuranId { get; set; }

    public string VerseOld { get; set; }

    public string VerseNoSign { get; set; }
    public int? PageNo { get; set; }
    public int? PartNo { get; set; }

    public int? HezbNo { get; set; }

    public int? RobNo { get; set; }
    public int? VerseNo { get; set; }
    public string VerseNoAr { get; set; }
    public int? SuraNo { get; set; } // navigation property to Sura
    [StringLength(250)]
    public string SuraName { get; set; }

    [StringLength(10)]
    public string Sound { get; set; } // h 

    public int? Id { get; set; }

    public string verse { get; set; }

    public string Verse { get; set; }

    public string SearchAyaa { get; set; } // tODO: what is this field

    public int? NoOfWords { get; set; }

    public int? NoOfLetters { get; set; }

    //[OldName("no_of_haraka")]
    //public int? NoOfHaraka { get; set; }

    public int? NoOfGhonna { get; set; }

    public int? NoOfGlala { get; set; }
}