// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
 
public partial class Quran
{
    /// <summary>
    /// old name: id
    /// </summary>
    public int? Id { get; set; }

    /// <summary>
    /// old name: QuranID
    /// </summary>
    public int? QuranId { get; set; }

    /// <summary>
    /// old name: verse
    /// </summary>
    public string Verse { get; set; }

    /// <summary>
    /// old name: verseNoSign
    /// </summary>
    public string VerseNoSign { get; set; }

    public int? PageNo { get; set; }
    public int? PartNo { get; set; }

    /// <summary>
    /// old name: hezbNo
    /// </summary>
    public int? HezbNo { get; set; }

    /// <summary>
    /// old name: rob3No
    /// </summary>
    public int? Rob3No { get; set; }

    public int? VerseNo { get; set; }
    public string VerseNoAr { get; set; }
    public int? SuraNo { get; set; }
    public string SuraName { get; set; }

    /// <summary>
    /// old name: sound
    /// </summary>
    public string Sound { get; set; }

    /// <summary>
    /// old name: img_warsh
    /// </summary>
    public string ImgWarsh { get; set; }

    /// <summary>
    /// old name: search_ayaa
    /// </summary>
    public string SearchAyaa { get; set; }

    /// <summary>
    /// old name: verse3_old
    /// </summary>
    public string Verse3Old { get; set; }

    /// <summary>
    /// old name: 2verse
    /// </summary>
    public string _2verse { get; set; }
}