// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Table("reciters", Schema = "quran_quran2")]
[OldName("reciters")]
public partial class Reciter
{
    [Key]
    [OldName("ReciterID")]
    public int ReciterId { get; set; }

    [Required]
    [OldName("ar_name")]
    public string ArName { get; set; }

    [Required]
    [OldName("en_name")]
    public string EnName { get; set; }

    [Required]
    [OldName("folder")]
    public string Folder { get; set; }

    [OldName("karat")]
    public int Karat { get; set; } // nivgation property to reciter_karat
}