// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

/// <summary>
//بالعربي بقا جدول القراء 
/// </summary>
public partial class Reciter 
{
    public int Id { get; set; }

    public string ArName { get; set; }

    public string EnName { get; set; }

    public string Folder { get; set; }

    public int KaratId { get; set; } // nivgation property to reciter_karat

}