// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Sura
{
    public int Id { get; set; }
    public int? SuraNo { get; set; }
    [MaxLength(50)]
    public string? SuraName { get; set; }
    public int? VersesNumber { get; set; }
    [MaxLength(20)]
    public string? Type { get; set; }
}

public partial class SuraDetail
{
    public int Id { get; set; }
    public int? SuraId { get; set; }

    public string? Title { get; set; }

    public string? SabbTasmia { get; set; }

    public string? Taareef { get; set; }

    public string? SabbNzol { get; set; }

    public string? Fadl { get; set; } // TODO: For what?

    public string? Mwadee { get; set; }

}
