// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Table("sura_sound", Schema = "quran_quran2")]
[OldName("sura_sound")]
public partial class SuraSound
{
    [Key]
    [OldName("SuraNo")]
    public long SuraNo { get; set; }

    [StringLength(50)]
    [OldName("SuraName")]
    public string SuraName { get; set; }
    [OldName("Verses")]
    public int? Verses { get; set; }

    [Required]
    [OldName("Type")]
    [StringLength(255)]
    public string Type { get; set; }

    [Required]
    [OldName("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [OldName("no_of_words")]
    public int NoOfWords { get; set; }

    [OldName("no_of_letters")]
    public int NoOfLetters { get; set; }

    [OldName("no_of_ghonna")]
    public int NoOfGhonna { get; set; }

    [OldName("no_of_glala")]
    public int NoOfGlala { get; set; }
}