﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Sverse
{
    public long SverseNo { get; set; }

    [StringLength(50)]
    public string SverseName { get; set; }
    public int? Verses { get; set; }
    [StringLength(255)]
    public string Type { get; set; }

    [StringLength(255)]
    public string Title { get; set; }
}