﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class TafseerNaboy
{
    public int? Id { get; set; }
    public int? VerseNo { get; set; }

    public int? Selid { get; set; }
    public int? SuraNo { get; set; } // TODO: if it isn't a forignkey change to SuraNumber

    public string Taraf { get; set; }

    [StringLength(100)]
    public string BookName { get; set; }

    public string HadithTxt { get; set; }

    public string HadithSearch { get; set; } // TODO: for what is this column

    public int? Status { get; set; }
}