﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class TafseerBook
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Book { get; set; }

    [Required]
    public string FieldQ { get; set; } //TODO

    [Required]
    public string Details { get; set; } //TODO

    public int Feature { get; set; } //TODO

    public int Date { get; set; } //TODO

    public int Type { get; set; } //TODO

    //[OldName("active")]
    //public short Active { get; set; }

    //[OldName("books_full")]
    //public short BooksFull { get; set; }
}