// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
//[Table("tafseeer", Schema = "quran_quran2")]
public partial class Tafseeer
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("QuranID")]
    public int? QuranId { get; set; } // navigation property to Quran
    [OldName("Verse")]
    public string Verse { get; set; }

    [OldName("GVerse")]
    public string Gverse { get; set; }

    [OldName("elgalalen")]
    public string Elgalalen { get; set; }

    [OldName("ibnkathir")]
    public string Ibnkathir { get; set; }
    [OldName("PageNo")]
    public int? PageNo { get; set; }
    [OldName("PartNo")]
    public int? PartNo { get; set; }
    [OldName("VerseNo")]
    public int? VerseNo { get; set; }
    [OldName("SuraName")]
    [StringLength(50)]
    public string SuraName { get; set; }
    [OldName("SuraNo")]
    public int? SuraNo { get; set; } // navigation property to Sura

    [OldName("tabary")]
    public string Tabary { get; set; }

    [OldName("mo7et")]
    public string Mohet { get; set; }

    [OldName("kortoby")]
    public string Kortoby { get; set; }

    [OldName("safwa")]
    public string Safwa { get; set; }

    [OldName("kashaf")]
    public string Kashaf { get; set; }

    [OldName("zelal")]
    public string Zelal { get; set; }

    [OldName("sa3dy")]
    public string Saady { get; set; }

    [OldName("kadeer")]
    public string Kadeer { get; set; }

    [OldName("elmoysar")]
    public string Elmoysar { get; set; }

    [OldName("wa7dy")]
    public string Wahdy { get; set; }

    [OldName("qatan")]
    public string Qatan { get; set; }

    [OldName("ezzsalam")]
    public string Ezzsalam { get; set; }

    [OldName("waseet")]
    public string Waseet { get; set; }

    [OldName("baedawy")]
    public string Baedawy { get; set; }

    [OldName("short_ibnkathir")]
    public string ShortIbnkathir { get; set; }

    [OldName("aysar")]
    public string Aysar { get; set; }

    [OldName("ba3awy")]
    public string Baawy { get; set; }

    [OldName("nasafy")]
    public string Nasafy { get; set; }

    [OldName("mawrdy")]
    public string Mawrdy { get; set; }

    [OldName("montkab")]
    public string Montkab { get; set; }

    [OldName("hatem")]
    public string Hatem { get; set; }

    [OldName("bnothemen")]
    public string Bnothemen { get; set; }

    [OldName("mafateh")]
    public string Mafateh { get; set; }

    [OldName("mara7")]
    public string Marah { get; set; }

    [OldName("mokatel")]
    public string Mokatel { get; set; }

    [OldName("adwa")]
    public string Adwa { get; set; }

    [OldName("ta7reer")]
    public string Tahreer { get; set; }

    [OldName("safwat")]
    public string Safwat { get; set; }

    [OldName("arafa")]
    public string Arafa { get; set; }

    [OldName("many")]
    public string Many { get; set; }

    [OldName("sha3rawy")]
    public string Sharawy { get; set; }

    [OldName("manar2")]
    public string Manar2 { get; set; }

    [OldName("manar")]
    public string Manar { get; set; }

    [OldName("dor")]
    public string Dor { get; set; }
}