// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
//[Table("tafseer_naboy", Schema = "quran_quran2")]
[OldName("tafseer_naboy")]
public partial class TafseerNaboy
{
    [OldName("id")]
    public int? Id { get; set; }
    [OldName("VerseNo")]
    public int? VerseNo { get; set; }

    [OldName("selid")]
    public int? Selid { get; set; }
    [OldName("SuraNo")]
    public int? SuraNo { get; set; } // TODO: if it isn't a forignkey change to SuraNumber

    [OldName("taraf")]
    public string Taraf { get; set; }

    [OldName("book_name")]
    [StringLength(100)]
    public string BookName { get; set; }

    [OldName("hadith_txt")]
    public string HadithTxt { get; set; }

    [OldName("hadith_search")]
    public string HadithSearch { get; set; } // TODO: for what is this column

    [OldName("status")]
    public int? Status { get; set; }
}