// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
//[Table("tafseer", Schema = "quran_quran2")]
public partial class Tafseer
{
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("QuranID")]
    public int? QuranId { get; set; }

    public string Verse { get; set; }

    [OldName("GVerse")]
    public string Gverse { get; set; }

    [OldName("elgalalen")]
    public string Elgalalen { get; set; }

    [OldName("ibnkathir")]
    public string Ibnkathir { get; set; }
    [OldName("PageNo")]
    public int? PageNo { get; set; }
    [OldName("PartNo")]
    public int? PartNo { get; set; }
    [OldName("VerseNo")]
    public int? VerseNo { get; set; }
    [OldName("SuraName")]
    [StringLength(50)]
    public string SuraName { get; set; }
    [OldName("SuraNo")]
    public int? SuraNo { get; set; }

    [OldName("tabary1")]
    public string Tabary1 { get; set; }

    [OldName("mo7et")]
    public string Mohet { get; set; }

    [OldName("kortoby")]
    public string Kortoby { get; set; }

    [OldName("safwa")]
    public string Safwa { get; set; }

    [OldName("kashaf")]
    public string Kashaf { get; set; }

    [OldName("zelal")]
    public string Zelal { get; set; }

    [OldName("sa3dy")]
    public string Saady { get; set; }

    [OldName("kadeer")]
    public string Kadeer { get; set; }

    [OldName("elmoysar")]
    public string Elmoysar { get; set; }

    [OldName("wa7dy")]
    public string Wahdy { get; set; }

    [OldName("qatan")]
    public string Qatan { get; set; }

    [OldName("ezzsalam")]
    public string Ezzsalam { get; set; }

    [OldName("elwaseet")]
    public string Elwaseet { get; set; }

    [OldName("baedawy")]
    public string Baedawy { get; set; }

    [OldName("short_ibnkathir")]
    public string ShortIbnkathir { get; set; }

    [OldName("aysar")]
    public string Aysar { get; set; }

    [OldName("ba3awy")]
    public string Baaawy { get; set; }

    [OldName("nasafy")]
    public string Nasafy { get; set; }

    [OldName("montkab")]
    public string Montkab { get; set; }

    [OldName("mawrdy")]
    public string Mawrdy { get; set; }

    [OldName("hatem")]
    public string Hatem { get; set; }

    [OldName("bnothemen")]
    public string Bnothemen { get; set; }

    [OldName("mafateh")]
    public string Mafateh { get; set; }

    [OldName("mara7")]
    public string Mara7 { get; set; }

    [OldName("mokatel")]
    public string Mokatel { get; set; }

    [OldName("adwa")]
    public string Adwa { get; set; }

    [OldName("ta7reer")]
    public string Tahreer { get; set; }

    [OldName("safwat")]
    public string Safwat { get; set; }

    [OldName("arafa")]
    public string Arafa { get; set; }

    [OldName("many")]
    public string Many { get; set; }

    [OldName("sha3rawy")]
    public string Sharawy { get; set; }

    [OldName("manar2")]
    public string Manar2 { get; set; }

    [OldName("manar")]
    public string Manar { get; set; }

    [OldName("maser")]
    public string Maser { get; set; }

    [OldName("dor")]
    public string Dor { get; set; }

    [OldName("zahra")]
    public string Zahra { get; set; }

    [OldName("saood")]
    public string Saood { get; set; }

    [OldName("moqatel")]
    public string Moqatel { get; set; }

    [OldName("dorar")]
    public string Dorar { get; set; }

    [OldName("qasmi")]
    public string Qasmi { get; set; }

    [OldName("mafateh1")]
    public string Mafateh1 { get; set; }

    [OldName("sa3dy1")]
    public string Saady1 { get; set; }

    [OldName("zelal1")]
    public string Zelal1 { get; set; }

    [OldName("wageez")]
    public string Wageez { get; set; }

    [OldName("mason")]
    public string Mason { get; set; }

    [OldName("kashaf1")]
    public string Kashaf1 { get; set; }

    [OldName("bian")]
    public string Bian { get; set; }

    [OldName("mojahed")]
    public string Mojahed { get; set; }

    [OldName("sofian")]
    public string Sofian { get; set; }

    [OldName("ibnkathirturkey")]
    public string Ibnkathirturkey { get; set; }

    [OldName("tabaryturkey")]
    public string Tabaryturkey { get; set; }

    [OldName("saood2")]
    public string Saood2 { get; set; }

    [OldName("ta7reer2")]
    public string Tahreer2 { get; set; }

    [OldName("tasheel")]
    public string Tasheel { get; set; }

    [OldName("razzaq")]
    public string Razzaq { get; set; }

    [OldName("baseet")]
    public string Baseet { get; set; }

    [OldName("eegy")]
    public string Eegy { get; set; }

    [OldName("mara3i")]
    public string Maraai { get; set; }

    [OldName("3azb")]
    public string _eazb { get; set; }

    [OldName("hatem1")]
    public string Hatem1 { get; set; }

    [OldName("safwat1")]
    public string Safwat1 { get; set; }

    [OldName("adwa1")]
    public string Adwa1 { get; set; }

    [OldName("kashaf2")]
    public string Kashaf2 { get; set; }

    [OldName("tabary_old")]
    public string TabaryOld { get; set; }

    [OldName("wa7dy1")]
    public string Wahdy1 { get; set; }

    [OldName("sha3rawy_new")]
    public string ShaarawyNew { get; set; }

    [OldName("ibnkathir_new")]
    public string IbnkathirNew { get; set; }

    [OldName("up_data")]
    public int? UpData { get; set; }

    [OldName("dor1")]
    public string Dor1 { get; set; }

    [OldName("saood1")]
    public string Saood1 { get; set; }

    [OldName("many1")]
    public string Many1 { get; set; }

    [OldName("many2")]
    public string Many2 { get; set; }

    [OldName("qasmi1")]
    public string Qasmi1 { get; set; }

    [OldName("manar1")]
    public string Manar1 { get; set; }

    [OldName("ta7reer1")]
    public string Tahreer1 { get; set; }

    [OldName("qatan1")]
    public string Qatan1 { get; set; }

    [OldName("books_full")]
    public int? BooksFull { get; set; }
}