// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Table("tafseer_book", Schema = "quran_quran2")]
[Index("Feature", Name = "feature")]
[OldName("tafseer_book")]
public partial class TafseerBook
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("book")]
    public string Book { get; set; }

    [Required]
    [OldName("Field_q")]
    public string FieldQ { get; set; }

    [Required]
    [OldName("details")]
    public string Details { get; set; }

    [OldName("feature")]
    public int Feature { get; set; }

    [OldName("date")]
    public int Date { get; set; }

    [OldName("type")]
    public int Type { get; set; }

    //[OldName("active")]
    //public short Active { get; set; }

    //[OldName("books_full")]
    //public short BooksFull { get; set; }
}