﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
//[Table("tafseeer", Schema = "quran_quran2")]
public partial class Tafseeer
{
    public int? Id { get; set; }

    public int? QuranId { get; set; } // navigation property to Quran
    public string Verse { get; set; }

    public string Gverse { get; set; }

    public string Elgalalen { get; set; }

    public string Ibnkathir { get; set; }
    public int? PageNo { get; set; }
    public int? PartNo { get; set; }
    public int? VerseNo { get; set; }
    //[OldName("SuraName")]
    //[StringLength(50)]
    //public string SuraName { get; set; }
    public int? SuraNo { get; set; } // navigation property to Sura

    public string Tabary { get; set; }

    public string Mohet { get; set; }

    public string Kortoby { get; set; }

    public string Safwa { get; set; }

    public string Kashaf { get; set; }

    public string Zelal { get; set; }

    public string Saady { get; set; }

    public string Kadeer { get; set; }

    public string Elmoysar { get; set; }

    public string Wahdy { get; set; }

    public string Qatan { get; set; }

    public string Ezzsalam { get; set; }

    public string Waseet { get; set; }

    public string Baedawy { get; set; }

    public string ShortIbnkathir { get; set; }

    public string Aysar { get; set; }

    public string Baawy { get; set; }

    public string Nasafy { get; set; }

    public string Mawrdy { get; set; }

    public string Montkab { get; set; }

    public string Hatem { get; set; }

    public string Bnothemen { get; set; }

    public string Mafateh { get; set; }

    public string Marah { get; set; }

    public string Mokatel { get; set; }

    public string Adwa { get; set; }

    public string Tahreer { get; set; }

    public string Safwat { get; set; }

    public string Arafa { get; set; }

    public string Many { get; set; }

    public string Sharawy { get; set; }

    public string Manar2 { get; set; }

    public string Manar { get; set; }

    public string Dor { get; set; }
}