﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class TafseerPage
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(200)]
    public string TafseerBook { get; set; } 

    public int PageNo { get; set; }

    public int VerseNo { get; set; }

    public int VerseCount { get; set; }

    public int SuraNo { get; set; } // navigation property to Sura

    [Required]
    [StringLength(500)]
    public string SuraName { get; set; }

    public short Repater { get; set; }

    public int MPageno { get; set; }

    public int MQuranid { get; set; }

    //[OldName("cheak_repater")]
    //public int CheakRepater { get; set; }

    //[OldName("updateTime")]
    //public DateTime UpdateTime { get; set; }
}