// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Table("tafseer_pages", Schema = "quran_quran2")]
public partial class TafseerPage
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("tafseer_book")]
    [StringLength(200)]
    public string TafseerBook { get; set; } 

    [OldName("page_no")]
    public int PageNo { get; set; }

    [OldName("verse_no")]
    public int VerseNo { get; set; }

    [OldName("verse_count")]
    public int VerseCount { get; set; }

    [OldName("sura_no")]
    public int SuraNo { get; set; } // navigation property to Sura

    [Required]
    [OldName("sura_name")]
    [StringLength(500)]
    public string SuraName { get; set; }

    [OldName("repater")]
    public short Repater { get; set; }

    [OldName("m_pageno")]
    public int MPageno { get; set; }

    [OldName("m_quranid")]
    public int MQuranid { get; set; }

    [OldName("cheak_repater")]
    public int CheakRepater { get; set; }

    [OldName("updateTime")]
    public DateTime UpdateTime { get; set; }
}