﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Tafseer
{
    public int? Id { get; set; }

    public int? QuranId { get; set; }

    public string Verse { get; set; }

    public string Gverse { get; set; }

    public string Elgalalen { get; set; }

    public string Ibnkathir { get; set; }
    public int? PageNo { get; set; }
    public int? PartNo { get; set; }
    public int? VerseNo { get; set; }
    [StringLength(50)]
    public string SuraName { get; set; }
    public int? SuraNo { get; set; }

    public string Tabary1 { get; set; }

    public string Mohet { get; set; }

    public string Kortoby { get; set; }

    public string Safwa { get; set; }

    public string Kashaf { get; set; }

    public string Zelal { get; set; }

    public string Saady { get; set; }

    public string Kadeer { get; set; }

    public string Elmoysar { get; set; }

    public string Wahdy { get; set; }

    public string Qatan { get; set; }

    public string Ezzsalam { get; set; }

    public string Elwaseet { get; set; }

    public string Baedawy { get; set; }

    public string ShortIbnkathir { get; set; }

    public string Aysar { get; set; }

    public string Baaawy { get; set; }

    public string Nasafy { get; set; }

    public string Montkab { get; set; }

    public string Mawrdy { get; set; }

    public string Hatem { get; set; }

    public string Bnothemen { get; set; }

    public string Mafateh { get; set; }

    public string Mara7 { get; set; }

    public string Mokatel { get; set; }

    public string Adwa { get; set; }

    public string Tahreer { get; set; }

    public string Safwat { get; set; }

    public string Arafa { get; set; }

    public string Many { get; set; }

    public string Sharawy { get; set; }

    public string Manar2 { get; set; }

    public string Manar { get; set; }

    public string Maser { get; set; }

    public string Dor { get; set; }

    public string Zahra { get; set; }

    public string Saood { get; set; }

    public string Moqatel { get; set; }

    public string Dorar { get; set; }

    public string Qasmi { get; set; }

    public string Mafateh1 { get; set; }

    public string Saady1 { get; set; }

    public string Zelal1 { get; set; }

    public string Wageez { get; set; }

    public string Mason { get; set; }

    public string Kashaf1 { get; set; }

    public string Bian { get; set; }

    public string Mojahed { get; set; }

    public string Sofian { get; set; }

    public string Ibnkathirturkey { get; set; }

    public string Tabaryturkey { get; set; }

    public string Saood2 { get; set; }

    public string Tahreer2 { get; set; }

    public string Tasheel { get; set; }

    public string Razzaq { get; set; }

    public string Baseet { get; set; }

    public string Eegy { get; set; }

    public string Maraai { get; set; }

    public string _eazb { get; set; }

    public string Hatem1 { get; set; }

    public string Safwat1 { get; set; }

    public string Adwa1 { get; set; }

    public string Kashaf2 { get; set; }

    public string TabaryOld { get; set; }

    public string Wahdy1 { get; set; }

    public string ShaarawyNew { get; set; }

    public string IbnkathirNew { get; set; }

    //[OldName("up_data")]
    //public int? UpData { get; set; }

    public string Dor1 { get; set; }

    public string Saood1 { get; set; }

    public string Many1 { get; set; }

    public string Many2 { get; set; }

    public string Qasmi1 { get; set; }

    public string Manar1 { get; set; }

    public string Tahreer1 { get; set; }

    public string Qatan1 { get; set; }

    //[OldName("books_full")]
    //public int? BooksFull { get; set; }
}