// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Table("tagwed_book", Schema = "quran_quran2")]
public partial class TagwedBook
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("book")]
    public string Book { get; set; }

    [OldName("Field_q")]
    public string FieldQ { get; set; }
}