// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Tagwed
{
    public int? QuranId { get; set; } // Foreign Key to Quran.ID
    public string Verse { get; set; }

    public string Gverse { get; set; }
    public int? PageNo { get; set; }
    public int? PartNo { get; set; }
    public int? VerseNo { get; set; }
    [StringLength(50)]
    public string SuraName { get; set; }
    public int? SuraNo { get; set; } // Foreign Key to Sura table

    public string Tagwed1 { get; set; }

    public string Tagen { get; set; }
}