// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Table("t_lang", Schema = "quran_quran2")]
[Index("Id", Name = "id")]
[OldName("t_lang")]
public partial class TLang
{
    [OldName("lang")]
    public string Lang { get; set; }

    [OldName("sura")]
    public string Sura { get; set; }

    [OldName("name")]
    public string Name { get; set; }

    [Key]
    [OldName("id")]
    public int Id { get; set; }
}