// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class TragemBook
{
    public int Id { get; set; }

    [Required]
    public string Book { get; set; }//TODO: shoud be Name 

    public string FieldQ { get; set; }
}