// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Tragem
{
    public int? Id { get; set; }

    public int? QuranId { get; set; } // navigation key to Quran table

    public string Verse { get; set; }

    public string Gverse { get; set; }

    public string English { get; set; }

    public string English2 { get; set; }

    public string EngAhmedAli { get; set; }

    public string EngYusufAli { get; set; }

    public string EngQarai { get; set; }

    public string EngAhmedRazaKhan { get; set; }

    public string EngArberry { get; set; }

    public string EngAsad { get; set; }

    public string EngDaryabadi { get; set; }

    public string EngHilaliAndKhan { get; set; }

    public string EngClearQuranGod { get; set; }

    public string EngClearQuranAllah { get; set; }

    public string EngCommunityGod { get; set; }

    public string EngCommunityAllah { get; set; }

    public string EngKhattab { get; set; }

    public string EngMaududi { get; set; }

    public string EngMubarakpuri { get; set; }

    public string EngPickthall { get; set; }

    public string EngSarwar { get; set; }

    public string EngQaribullahAndDarwish { get; set; }
    public string Germany { get; set; }
    public int? PageNo { get; set; }
    public int? PartNo { get; set; }
    public int? VerseNo { get; set; }
    public string SuraName { get; set; }
    public int? SuraNo { get; set; } // navigation property to Sura

    public string Japanese { get; set; }

    public string Chinese { get; set; }

    public string Italy { get; set; }

    public string Fr { get; set; }

    public string Fr2 { get; set; } // todo : what is the difference between fr and fr2?

    public string Indo { get; set; }

    public string Kory { get; set; }

    public string Sahly { get; set; }

    public string Rusha { get; set; }

    public string Alb { get; set; }

    public string Sp { get; set; }

    public string Hendi { get; set; }

    public string Malawy { get; set; }

    public string Polg { get; set; }

    public string Polsh { get; set; }

    public string Posna { get; set; }

    public string Ty { get; set; }

    public string Fares { get; set; }

    public string Torki { get; set; }

    public string Azer { get; set; }

    public string Braz { get; set; }

    public string Sere { get; set; }

    public string Fin { get; set; }

    public string EnglishShaker { get; set; }

    public string German2 { get; set; }

    //[OldName("fh")]
    //public string Fh { get; set; }
}