// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[Keyless]
//[Table("words", Schema = "quran_quran2")]
[OldName("words")]
public partial class Word
{
    [OldName("wordid")]
    public int? Wordid { get; set; }

    [OldName("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [OldName("sura_id")]
    public int? SuraId { get; set; } // foreign key to sura.sura_id

    [OldName("QuranID")]
    public int? QuranId { get; set; } // foreign key to quran.quran_id

    [OldName("score")]
    public int? Score { get; set; }

    [OldName("pageno")]
    public int? Pageno { get; set; }
}