// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Word
{
    public int? Wordid { get; set; }

    [StringLength(255)]
    public string Title { get; set; }

    public int? SuraId { get; set; } // foreign key to sura.sura_id

    public int? QuranId { get; set; } // foreign key to quran.quran_id

    //[OldName("score")]
    //public int? Score { get; set; }

    public int? Pageno { get; set; }
}